article/urls.py
from django.urls import path
from . import views
app_name = 'article'
urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article/<int:id>/', views.article_page, name='article_page'),
    path('add/', views.article_add, name='article_add'),
    path('artikel/<int:id>/delete/', views.article_delete, name='article_delete')
]

komentar/urls.py
from django.urls import path
from . import views

app_name = 'komentar'
urlpatterns = [
    path('add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:id_artikel>/<int:id_komentar>', views.delete_comment, name='delete_comment')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwb01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('relawan.urls')),
    path('', include('article.urls')),
    path('', include('komentar.urls'))
]

relawan/urls.py
from django.urls import re_path

from . import views

app_name = 'relawan'

urlpatterns = [
    re_path(r'^relawan', views.relawan, name='relawan'),
    re_path('formrelawan', views.formRelawan, name='formrelawan'),
    re_path('saverelawan', views.saverelawan),
]

article/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Article(models.Model):
    artikel = models.CharField(max_length=50, help_text='Nama Artikel')
    penulis = models.CharField(max_length=50, help_text='Nama Penulis')
    deskripsi = models.TextField(help_text='Deskripsi')
    tanggal_penulisan = models.DateTimeField(default=timezone.now,help_text='Tanggal Penulisan')
    def __str__(self):
        return "{} | {} | {} | {}".format(self.artikel, self.penulis, self.deskripsi, self.tanggal_penulisan)

komentar/models.py
from django.db import models
from django.utils import timezone
from article.models import Article

# Create your models here.
class Komentar(models.Model):
    commenter = models.CharField(max_length=20, default='Anonymous')
    comment = models.TextField()
    waktu = models.DateTimeField(default=timezone.now)
    artikel = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)

main/models.py
from django.db import models

# Create your models here.

relawan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class RelawanList(models.Model):
    display_name = models.CharField(max_length=60)
    alamat = models.CharField(max_length=200)
    donasi = models.CharField(max_length=40)

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        # artikel = forms.CharField(label="Nama Artikel",max_length=50,widget=forms.TextInput(attrs={"placeholder":"","class":"form-control",}))
        # penulis = forms.CharField(label="Penulis Artikel",max_length=50,widget=forms.TextInput(attrs={"placeholder":"","class":"form-control",}))
        # deskripsi = forms.CharField(label="Deskripsi",widget=forms.TextInput(attrs={"placeholder":"Tulis Konten Artikel Anda","class":"form-control",}))
        model = Article
        fields = ['artikel', 'penulis', 'deskripsi']
        labels = {
            'artikel':'Nama Artikel',
            'penulis':'Penulis Artikel',
            'deskripsi':'Deskripsi',
        }
        widgets = {
            'artikel':forms.TextInput(attrs={
                'placeholder':'',
                'class':'form-control',
            }),
            'penulis': forms.TextInput(attrs = {
                'placeholder':'',
                'class':'form-control',
            }),
            'deskripsi':forms.TextInput(attrs={
                'placeholder':'Tulis Konten Artikel Anda Disini',
                'class':'form-control',
            }),
        
        }

komentar/forms.py
from django import forms
from .models import Komentar

class KomentarForm(forms.ModelForm):
    class Meta:
        model = Komentar
        fields = ('commenter', 'comment')
        labels = {
            'commenter':'Nama',
            'comment':'Komentar',
        }

relawan/forms.py
from django import forms
from .models import RelawanList

class Input_Form(forms.ModelForm):
	class Meta:
		model = RelawanList
		fields = ['display_name','alamat','donasi']
		error_messages = {
			'required' : 'Please Type'
		}
	input_attrs = {
		'type' : 'text',
		'placeholder' : 'Nama'
	}
	alamat_input = {
		'type' : 'text',
		'placeholder' : 'Alamat'
	}
	donasi_input = {
		'type' : 'text',
		'placeholder' : 'Jumlah Donasi'
	}

	display_name = forms.CharField(label='', required=True, max_length=60, widget=forms.TextInput(attrs=input_attrs))
	alamat = forms.CharField(label='', required=True, max_length=200, widget=forms.TextInput(attrs=alamat_input))
	donasi = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=donasi_input))

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article
from .forms import ArticleForm
from komentar.forms import KomentarForm

# Create your views here.
def article_list(request):
    artikels = Article.objects.all()
    return render(request, 'article/landing.html', {'artikels':artikels})

def article_page(request, id):
    artikel = get_object_or_404(Article, id=id)
    list_komentar=artikel.komentar_set.all()

    response = {
        'artikel':artikel,
        'list_komentar':list_komentar,
    }

    if request.method == "POST":
        form = KomentarForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.artikel = artikel
            comment.save()
            return redirect('article:article_page', id=artikel.id)
    else:
        form = KomentarForm()
        response['form']=form

    return render(request, 'article/view.html', response)

def article_add(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            artikel = form.save()
            artikel.save()
            return redirect('article:article_page', id=artikel.id)
    else:
        form = ArticleForm()
        artikel = Article.objects.all()
        context = {'form':form,'artikel':artikel}
        return render(request, 'article/form.html', context)

def article_delete(request, id):
    Article.objects.get(id=id).delete()
    return redirect('article:article_list')

komentar/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *

# Create your views here.
def add_comment(request, id):
    artikel = get_object_or_404(Article, id=id)

    if request.method == "POST":
        form = KomentarForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.artikel = artikel
            comment.save()
            return redirect('article:article_page', id=id)
    else:
        
        response['form'] = KomentarForm()

    return render(request, 'article/view.html', response)

def delete_comment(request, id_artikel, id_komentar):
    Komentar.objects.get(id=id_komentar).delete()
    return redirect('article:article_page', id=id_artikel)

main/views.py
from django.shortcuts import render
import requests

def home(request):
    response = requests.get('https://api.kawalcorona.com/indonesia/provinsi')
    data = response.json()
    kasus = []
    for o in data:
        datanya = {}
        datanya['provinsi'] = o['attributes']['Provinsi']
        datanya['kasus_positif'] = o['attributes']['Kasus_Posi']
        datanya['kasus_sembuh'] = o['attributes']['Kasus_Semb']
        datanya['kasus_meninggal'] = o['attributes']['Kasus_Meni']
        kasus.append(datanya)
    return render(request, 'main/home.html', {
        'data': kasus,
    })

relawan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import RelawanList

# Create your views here.
def relawan(request):
	relawans = RelawanList.objects.all()
	response = {'relawans' : relawans}
	return render(request, 'main/relawan.html', response)


def formRelawan(request):
	response = 	{'input_form' : Input_Form}
	return render(request, 'main/formRelawan.html', response)

def saverelawan(request):
	form = Input_Form(request.POST)
	if request.method == 'POST':
		if form.is_valid():
				form.save()
				return HttpResponseRedirect('/relawan')
		else:
				return HttpResponseRedirect('/formrelawan')

article/templates/article/form.html
{% extends 'base.html' %}
{% block content%}
<div class="dark">
    <h1>Artikel Baru</h1>
    <div class="container">
        <form method="POST" class="">{% csrf_token %}
            {% for field in form %}
            <div class="container p-2">
                <label for="{{ field.name }}">{{ field.label }}</label>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <div class="row p-3">
                <div class="col-auto my-auto">
                    <button type="submit" class="btn btn-form">Simpan</button>
                </div>
                <div class="col-auto my-auto">
                    <a class="btn btn-danger" href="{% url 'article:article_list' %}">Batal</a>
                </div>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}

article/templates/article/landing.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;700&display=swap" rel="stylesheet">
<link href="{% static 'css/TK2style.css' %}" rel="stylesheet">
{% endblock %}

{% block navcolor %}navbar-light{% endblock %}
{% block content %}
<div>
    <div class="container p-5">
        <h1>List Artikel</h1>
        
        <div class="container">
            <div class="row p-5">
                <div class="col"></div>
                <div class="col-auto">
                    <a class="btn btn-info" href="{% url 'article:article_add' %}">
                        Tambah Artikel
                    </a>
                </div>
                <div class="col"></div>
            </div>
            
            {% for artikel in artikels %}
            <div class="container p-3">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'article:article_page' id=artikel.id %}"><h2>{{ artikel.artikel }}</h2></a>
                        <div class="container">
                            <p>Penulis: {{ artikel.penulis }}</p>
                            <p>Tanggal Penulisan: {{ artikel.tanggal_penulisan }}</p>
                        </div>
                    </div>
                    <div class="col-auto my-auto">
                        <a class="btn btn-danger" href="{% url 'article:article_delete' id=artikel.id %}">Hapus</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/view.html
{% extends 'base.html' %}

{% block content%}
<div class="dark">
    <div class="container pt-5">
        <h1>{{ artikel.nama }}</h1>
        <div class="container p-5">
            <h3>Penulis: {{ artikel.penulis }}</h3>
            <h3>Tanggal Penulisan: {{ artikel.tanggal_penulisan }}</h3>
            <h3>Deskripsi:</h3> 
            <div class="container">
                <p>{{ artikel.deskripsi }}</p>
            </div>
            <div class="d-flex justify-content-center p-5">
                <a class="btn btn-info" href="{% url 'article:article_list' %}">Back</a>
            </div>
            <hr>
            <form method="POST" class="">{% csrf_token %}
                {% for field in form %}
                <div class="container p-2">
                    <label for="{{ field.name }}">{{ field.label }}</label>
                    <div>
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <div class="row p-3">
                    <div class="col-auto my-auto">
                        <button type="submit" class="btn btn-form">Simpan</button>
                    </div>
                </div>
            </form> 
            <h3>Komentar:</h3>
            {% for komentar in list_komentar %}
            <div>
                <h4>{{ komentar.commenter }}</h5>
                <h5>{{ komentar.waktu }}</h5>
                <p>
                    {{ komentar.comment }}
                </p>
                <div class="col-auto my-auto">
                    <a class="btn btn-danger" href="{% url 'komentar:delete_comment' id_artikel=artikel.id id_komentar=komentar.id %}">Hapus Komentar</a>
                </div>
                <br>
            </div>
            {% endfor %}
        </div>
    </div>    
</div>

{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>B01</title>

{% endblock meta %}

{% block content %}
 <!-- <h1>Hello, world!</h1>-->
  <div>
  <div class="card" style="padding: 10px">
  	<p><a style="background: transparent; " href="{% url 'main:home' %}">Beranda</a></p>
  </div>

  <div class="card" style="margin-top: 30px;">
  	<div class="card-body">
  		<h2>
  			Kasus Covid di Indonesia
  		</h2>
  	</div>
  	<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
				<tr>			
					<th>Provinsi</th>
					<th>Kasus Positif</th>
					<th>kasus Sembuh</th>
					<th>kasus Meninggal</th>
				</tr>
			</thead>
			<tbody>
                {% for covid in data %}
				<tr>				
					<td>{{covid.provinsi}}</td>
					<td>{{covid.kasus_positif}}</td>
					<td>{{covid.kasus_sembuh}}</td>
					<td>{{covid.kasus_meninggal}}</td>
                </tr>
                {% endfor %}
			</tbody>
		</table>
  </div>
  </div><br><br>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
			    $('#example').DataTable( {
			        "order": [[ 1, "desc" ]]
			    } );
			} );
    </script>
    <style type="text/css">
	div {
		margin-left: auto;
		margin-right: auto;
		width: 90%;
		font-size: 12px;
	}
	.card-body{
		margin-left: auto;
		margin-right: auto;
		width: 50%;
		text-align: center;
	}
	.row {
		margin-left: auto;
		margin-right: auto;
		width: 80%;
	}
	p {
		margin: 0px;
		font-size: 17px;
	}

	.pagination {
		position: inherit;
	}

	table {
		font-size: 12px;
	}


</style>
{% endblock content %}

relawan/templates/main/formRelawan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5 Randa Mata Kuliah</title>
{% endblock meta %}

{% block content %}
  <section id="">
		<div class="container">
		<div class="card col-md-12">
			<h3>Silakan Masukan Data</h3><br>
			<form action="saverelawan" method="POST">
				{% csrf_token %}
				Nama: {{ input_form.display_name }}<br><br>
				Alamat: {{ input_form.alamat }}<br><br>
				Jumlah Donasi : {{ input_form.donasi }}<br><br>
				<input id="submit" type="submit" value="Submit">
			</form>
	    </div>

	</div>
<br>
	</section>

	<style type="text/css">
		input {
			padding: 5px 5px 5px 5px;
			border-radius: 10px;
			border-width: 1px;
			width: 100%;
			border-color: white;
		}
		.container {
			font-size: 15px;
			margin-bottom: 100px;

		}
		#submit {
			width: 30%;
			background-color: #34F6F2;
			color: white;
			font-weight: bold;
		}
		#submit:hover {
			width: 30%;
			
			background-color: #07A3D5;
			color: white;
			font-weight: bold;
		}
	</style>
	
{% endblock content %}

relawan/templates/main/relawan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cov19 Relawan</title>

{% endblock meta %}

{% block content %}
 <!-- <h1>Hello, world!</h1>-->
  <div>
  <div class="card" style="padding: 10px">
  	<p><a style="background: transparent; " href="{% url 'relawan:relawan' %}">Relawan</a></p>
  </div>

<div class="card" style="margin-top: 30px !important">
	    	<div class="" style="margin-top: 20px !important"></div>
	    	<div class="">
	    		
	    	<table class="table" id="myTable">
	    		<button><a id="link" href="/formrelawan">Tambah Relawan</a></button>
	    		<thead >
	    		<tr>
	    			<th>Nama</th>
	    			<th>Alamat</th>
	    			<th>Donasi</th>
	    		</tr>
	    		</thead>
			{% if relawans %}
			<tbody>
				{% for relawan in relawans %}
		
				<tr>
					<td>{{ relawan.display_name }}</td>
					<td>{{ relawan.alamat }}</td>
					<td>{{ relawan.donasi }}</td>
						
				</tr>
				
		<br/>
		{% endfor %}
		</tbody>
	{% endif %}
</table>
</div>

	    </div>

</div>

  
    <style type="text/css">
	div {
		margin-left: auto;
		margin-right: auto;
		width: 90%;
		font-size: 17px;
	}
	.card-body{
		margin-left: auto;
		margin-right: auto;
		width: 50%;
		text-align: center;
	}
	.row {
		margin-left: auto;
		margin-right: auto;
		width: 80%;
	}
	p {
		margin: 0px;
		font-size: 17px;
	}

	.pagination {
		position: inherit;
	}

	table {
		font-size: 12px;
	}
	button {
		border: none;
		padding: 10px 10px 10px 10px;
	}


</style>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/TK2style.css' %}">
    
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<nav>
	<ul id="myDIV">
  <li class="myPage">Cov19</li>
 <!-- <li class="links"><a class="bton" href="#kontak">Kontak</a></li>
  <li class="links"><a class="bton" href="#minat">Minat</a></li>-->
  <li class="links"><a class="bton" href="{% url 'article:article_list' %}" id="artikel">Artikel</a></li>
  <li class="links"><a class="bton" href="{% url 'relawan:relawan' %}">Relawan</a></li>
  <li class="links"><a class="bton" href="{% url 'main:home' %}">Beranda</a></li>
</ul>
</nav>
{% block content %}
  {% endblock content %}

<!--<footer>
	<div class="footer">
  <p>@B01_2020</p>
</div>
</footer>-->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>
</body>
  
</html>